- studyroom-app/src/components/CreateStudyForm.tsx
- studyroom-app/src/components/FilterBar.tsx
- studyroom-app/src/components/FormField.tsx
- studyroom-app/src/components/TagInput.tsx
- studyroom-app/src/pages/StudyListPage.tsx
- studyroom-app/src/styles/CreateStudyForm.css
- studyroom-app/src/styles/Modal.css
- studyroom-app/src/styles/TagInput.css
- studyroom-app/src/types/filter.ts
feat: [박태준] 사용자는 새로운 면접스터디를 직접 생성할 수 있다. [JSF-5]
> feat: [박태준] 사용자는 새로운 면접스터디를 직접 생성할 수 있다. [JSF-5]

- studyroom-app/src/App.tsx
- studyroom-app/src/components/ApplicationCard.tsx
- studyroom-app/src/data/mockData.ts
- studyroom-app/src/pages/MyApplicationsPage.tsx
- studyroom-app/src/pages/StudyListPage.tsx
- studyroom-app/src/styles/ApplicationCard.css
- studyroom-app/src/styles/MyApplicationsPage.css
- studyroom-app/src/styles/StudyListPage.css
feat: [박태준] 사용자는 본인이 참가 신청한 스터디 목록과 참가신청 상태를 확인할 수 있다. [JSF-11]
참여신청한 스터디목록 클릭 시 상세페이지 이동 미구현
참여신청한 스터디목록이 없을 경우 '참가 신청한 면접스터디가 없습니다' 미출력
추후 update로 구현 예정
> feat: [박태준] 사용자는 본인이 참가 신청한 스터디 목록과 참가신청 상태를 확인할 수 있다. [JSF-11]

- studyroom-app/src/App.tsx
- studyroom-app/src/components/ApplicationCard.tsx
- studyroom-app/src/data/mockData.ts
- studyroom-app/src/pages/MyApplicationsPage.tsx
- studyroom-app/src/styles/ApplicationCard.css
- studyroom-app/src/styles/MyApplicationsPage.css
참가 신청한 목록이 없을 경우 [신청한 면접스터디 모임이 없습니다.] 출력 업데이트
> update: [박태준] 사용자는 본인이 참가 신청한 스터디 목록과 참가신청 상태를 확인할 수 있다. [JSF-11]

- main-container/module-federation.config.ts
- navigation-bar-app/module-federation.config.ts
- package-lock.json
- studyroom-app/module-federation.config.ts
- vue-ai-interview-app/src/ai-interview/pages/ai-interview.vue
- vue-ai-interview-app/src/ai-interview/pages/llm-test/ai-interview-llm.vue
- vue-ai-interview-app/src/router.ts
ai-interview 메인 페이지와 카메라 조정 까지 remote 성공
> update:[임운철]기존Job-stick의 AI-interview 가져오기 [JSF-9]

- studyroom-app/src/App.tsx
- studyroom-app/src/components/studyroom/AnnouncementForm.tsx
- studyroom-app/src/components/studyroom/Announcements.tsx
- studyroom-app/src/data/mockData.ts
- studyroom-app/src/pages/JoinedStudyRoom.tsx
- studyroom-app/src/styles/AnnouncementForm.css
- studyroom-app/src/styles/Announcements.css
- studyroom-app/src/styles/JoinedStudyRoom.css
feat: [박태준] 모임장은 면접스터디 모임에서 공지사항을 생성할 수 있다. [JSF-16]
> feat: [박태준] 모임장은 면접스터디 모임에서 공지사항을 생성할 수 있다. [JSF-16]

- studyroom-app/src/components/studyroom/AnnouncementDetail.tsx
- studyroom-app/src/components/studyroom/Announcements.tsx
- studyroom-app/src/data/mockData.ts
- studyroom-app/src/styles/AnnouncementDetail.css
- studyroom-app/src/styles/Announcements.css
feat: [박태준] 모임장은 면접스터디 모임에서 공지사항을 조회할 수 있다. [JSF-17]
> feat: [박태준] 모임장은 면접스터디 모임에서 공지사항을 조회할 수 있다. [JSF-17]

- studyroom-app/src/components/CreateStudyForm.tsx
- studyroom-app/src/pages/StudyListPage.tsx
1. update내역
- 스터디 생성 후 생성 모달창이 닫히지 않는 현상 보완 완료
- 생성이 완료되었다는 알럿창 확인 후 리스트페이지에서 생성이 안되는 현상 보완 완료
> update: [박태준] 사용자는 새로운 면접스터디를 직접 생성할 수 있다. [JSF-5]

- studyroom-app/src/components/CreateStudyForm.tsx
- studyroom-app/src/components/StudyDetailView.tsx
- studyroom-app/src/pages/StudyDetailPage.tsx
- studyroom-app/src/types/study.ts
1. update 내역
- 백 to 프론트 스터디룸 내용 수정(put, patch) 연동 완료
> update: [박태준] 모임장은 본인이 생성한 면접스터디 모임에 대한 내용을 수정할 수 있다. [JSF-49]

- studyroom-app/src/api/axiosInstance.ts
- studyroom-app/src/components/CreateStudyForm.tsx
- studyroom-app/src/components/FilterBar.tsx
- studyroom-app/src/data/mockData.ts
- studyroom-app/src/hooks/useAuth.ts
- studyroom-app/src/pages/MyApplicationsPage.tsx
- studyroom-app/src/pages/MyStudiesPage.tsx
- studyroom-app/src/pages/StudyDetailPage.tsx
1. chore
- 내 스터디 신청내역 : 검색창 및 지역, 직무필터 추가
- 참여중인 면접스터디 목록 : 검색창 및 지역, 직무필터 추가
> chore: [박태준] 검색창 및 지역, 직무필터 추가 적용

- studyroom-app/src/components/studyroom/Participants.tsx
- studyroom-app/src/pages/JoinedStudyRoom.tsx
1. chore
- 현재로그인 기준 참여중인 스터디모임 delete 기능 수정
> chore: [박태준] 면접스터디모임 DELETE(폐쇄,강퇴,탈퇴) 기능 수정

- studyroom-app/src/components/studyroom/AnnouncementDetail.tsx
- studyroom-app/src/components/studyroom/Announcements.tsx
- studyroom-app/src/hooks/useAuth.ts
- studyroom-app/src/types/study.ts
1. update
- 목업데이터 삭제 및 현재로그인값 기준 적용
- DB내 공지사항 목록조회, 상세조회 구현
- 모임장의 공지사항목록 상단고정 및 고정해제
> update: [박태준] 일반 참가자는 면접스터디 모임에서 공지사항을 조회할 수 있다. [JSF-20]

- mypage-app/src/components/MyPageLayout.tsx
- mypage-app/src/components/ProfileAppearanceCard.tsx
- mypage-app/src/components/ProfileAppearanceCardEdit.tsx
- navigation-bar-app/src/App.tsx
- 로그인 후 인증된 사용자가 아니면 로그인 알람 팝업 뜨도록 수정(navigationbarapp > App.tsx)
> feat: [정은선] 인증된 사용자만 마이페이지에 접근할 수 있다 [JSF-74]

- studyroom-app/src/pages/MyApplicationsPage.tsx
1. update
- 목업데이터 삭제
- 로그인 기반 백-프론트 연동테스트 완료
> update: [박태준] 사용자는 제출했던 스터디모임 지원을 취소할 수 있다. [JSF-77]

- package-lock.json
- package.json
- studyroom-app/src/components/studyroom/EventForm.tsx
- studyroom-app/src/components/studyroom/Schedule.tsx
- studyroom-app/src/pages/JoinedStudyRoom.tsx
- studyroom-app/src/types/study.ts
1. update
- 목업데이터 삭제
- 백-프론트 연동테스트 완료
- react-datepicker 라이브러리 추가[일정생성 시 시간체크 ui 개선]
> update: 모임장은 외부 채널 링크를 포함하여 모의면접 일정을 생성할 수 있다. [JSF-22]

- studyroom-app/src/components/studyroom/EventDetail.tsx
- studyroom-app/src/components/studyroom/Schedule.tsx
1. update
- 목업데이터 삭제
- 일정관리 수정기능 구현
- 백-프론트 연동테스트 완료
> update: [박태준] 스터디모임에서 본인이 등록한 일정을 수정할 수 있다. [JSF-79]

- studyroom-app/src/components/StudyRoomCard.tsx
- studyroom-app/src/components/studyroom/Participants.tsx
- studyroom-app/src/hooks/useAuth.ts
- studyroom-app/src/pages/JoinedStudyRoom.tsx
- studyroom-app/src/pages/StudyListPage.tsx
1. feat
- 모임내 모임장이 참가신청에 대하여 수락/거절하는 프론트 로직 구현
> feat: [박태준] 모임장은 스터디모임 지원자의 참가 신청을 승인하거나 거절할 수 있다. [JSF-108]

- vue-account-app/src/account/utility/axiosInstance.ts
- vue-account-app/src/bootstrap.tsx
- vue-account-app/src/github/stores/githubAuthenticationActions.ts
- vue-account-app/src/router.ts
- vue-account-app/src/security/admin/adminFlow.ts
- vue-account-app/src/security/admin/adminGuards.ts
- vue-account-app/src/security/admin/adminSession.ts
- vue-account-app/src/security/admin/index.ts
- vue-account-app/src/security/admin/security-config.ts
jsf-119 init 처리 이후 불가피하게 수정이 미흡했던 path 부분 수정
> feat: [이승현] 보안 강화를 위해 관리자는 관리자 전용 인증 절차를 따른다 [JSF-119]

- studyroom-app/src/components/studyroom/Announcements.tsx
- studyroom-app/src/components/studyroom/ApplicationManagement.tsx
- studyroom-app/src/components/studyroom/AttendanceManagement.tsx
- studyroom-app/src/components/studyroom/EventDetail.tsx
- studyroom-app/src/components/studyroom/Participants.tsx
- studyroom-app/src/components/studyroom/Schedule.tsx
- studyroom-app/src/components/studyroom/TestInterview.tsx
> chore: [박태준] 모임장은 멤버들의 출석 현황을 관리할 수 있다. [JSF-127]

- mypage-app/src/api/profileAppearanceApi.ts
- mypage-app/src/pages/AccountProfileEdit.tsx
- 사용자가 "사진 변경" 버튼을 클릭하면 로컬 파일 선택 창이 뜬다.
- 업로드 완료 시 사용자 프로필 사진이 즉시 갱신된다.
- 업로드 실패 시 에러 메시지가 표시된다.
> feat: [정은선] 사용자는 회원정보 수정 메뉴에서 사진 변경 버튼을 눌러 프로필 사진을 교체할 수 있다 [JSF-131]

- studyroom-app/src/api/axiosInstance.ts
- studyroom-app/src/hooks/useAuth.ts
1. chore
- studyroom-app useAuth 내 userProfile 값 삭제
- isLoggedIn, nickname으로 변경
- axois 내 유효 userToken값 검사 삭제
> chore: [박태준] 로그인 정책에 맞게studyroom-app 내 useAuth를 수정합니다. [JSF-133]

- studyroom-app/src/api/axiosInstance.ts
- studyroom-app/src/components/studyroom/Participants.tsx
- studyroom-app/src/components/studyroom/ParticipantsReportModal.tsx
1. feat
- 스터디모임 참여인원 탭 내 각 멤버들에 대하여 신고기능 추가
> feat: [박태준] 스터디모임 내 모든 참가자는 같은 모임 내 멤버를 신고할 수 있다. [JSF-135]

- mypage-app/src/api/profileAppearanceApi.ts
- mypage-app/src/api/userLevelApi.ts
- mypage-app/src/api/userTitleApi.ts
- mypage-app/src/api/userTrustScoreApi.ts
- mypage-app/src/components/dashboard/DashboardSection.tsx
- mypage-app/src/components/dashboard/LevelSection.tsx
- mypage-app/src/components/dashboard/TitleSection.tsx
- mypage-app/src/components/layout/MyPageLayout.tsx
- mypage-app/src/components/modals/TrustScoreModal.tsx
- mypage-app/src/components/profile/ProfileAppearanceCard.tsx
- mypage-app/src/pages/UserHistoryPage.tsx
> refactor: [정은선] profileAppearance API 분리
